### ISSUE TITLE
Optimizer Not Respecting Allowed Vertices

### ISSUE THREAD

**Issue by ChocolateBiscuit** [amir90/MagicClay#3]
Trying to reproduce your results, running the demo, it appears that the method is not respecting the allowed_vertices_ids.txt. Running the spot with angel wings example, these are the results at 1800 iterations: 
<img width="904" alt="image" src="https://github.com/user-attachments/assets/5fcc8ebe-d18d-4bf1-8d06-89d8bd606879">

**Comment by ChocolateBiscuit** [comment]
On a quick second glance, I might've misunderstood the outputs, it seems like the second row is the actual optimized mesh wrt to the allowed vertices?

**Comment by amirbarda** [comment]
yes, second row is the mesh

**Comment by ChocolateBiscuit** [comment]
Thanks for clarifying! Is the first row visualizing just what SDS without limitations would produce?

**Comment by amirbarda** [comment]
Exactly! The initialization steps and the hybrid losses are meant to align the SDF and mesh enough so that the right geometry is created in the right place on the SDF, but in general the SDF is mainly influenced by the SDS loss.
