### ISSUE TITLE
The faces of mesh in the editing region fracture

### ISSUE THREAD

**Issue by 1211186431** [amir90/MagicClay#4]
Hi, great work on this project!
I’m encountering an issue while training with custom data. As shown in the screenshot
![WX20241130-105927@2x](https://github.com/user-attachments/assets/9286ba79-c855-4404-9ee9-ca79b13f13af)
Specifically, after reaching the `initial_fit_steps`  during training, the faces of mesh in the editing region begin to fracture. Could you please help me understand why this issue occurs? Is it because the mesh and the SDF field are not properly aligned?

**Comment by amirbarda** [comment]
Hi! I think your meshes have disconnected edges along the texture borders. Open your mesh in a program like MeshLab and try to see that there are no border edges, if there are a "merge close vertices" operation (in the filters tab) should resolve this.

**Comment by 1211186431** [comment]
Thank you for your suggestion! I followed the method you provided and the issue has been resolved. It seems the problem was with the original mesh I provided.
